sudo:     false
language: erlang
install:  "true" # don't let travis run get-deps
before_script:
    - wget https://s3.amazonaws.com/rebar3/rebar3
    - chmod +x rebar3
script:   "./rebar3 do xref, dialyzer, eunit"
otp_release:
    - 18.2
    - 19.3
cache:
  directories:
  - _build
  - .cache/rebar3
